import os
import uuid
import logging
from io import BytesIO
from typing import Dict, Any, Optional
from minio import Minio
from docx import Document
from openpyxl import Workbook
from weasyprint import HTML
from app.core.config import settings
from app.core.celery_app import celery_app

logger = logging.getLogger(__name__)

class ExportService:
    def __init__(self):
        self.client = None
        if settings.MINIO_ENDPOINT:
            try:
                self.client = Minio(
                    settings.MINIO_ENDPOINT.replace("http://", "").replace("https://", ""),
                    access_key=settings.MINIO_ACCESS_KEY,
                    secret_key=settings.MINIO_SECRET_KEY,
                    secure=False
                )
            except Exception as e:
                logger.error(f"MinIO Initialization Error: {e}")

    def generate_markdown(self, data: Dict[str, Any]) -> bytes:
        content = f"# Business Plan: {data.get('company_name', 'Untitled')}\n\n"
        for item in data.get('answers', []):
            content += f"## {item['question']}\n{item['answer']}\n\n"
        return content.encode("utf-8")

    def generate_docx(self, data: Dict[str, Any]) -> bytes:
        """
        Generates a professional DOCX document.
        In a production scenario, this would use a docxtpl with a branded .docx file.
        """
        doc = Document()
        doc.add_heading(f"Business Plan: {data.get('company_name', 'Untitled')}", 0)
        
        for item in data.get('answers', []):
            doc.add_heading(item['question'], level=1)
            doc.add_paragraph(item['answer'])
            
        file_stream = BytesIO()
        doc.save(file_stream)
        return file_stream.getvalue()

    def generate_pdf(self, data: Dict[str, Any]) -> bytes:
        """
        Generates a premium PDF using WeasyPrint with cover page and styling.
        """
        company_name = data.get('company_name', 'Untitled Business')
        industry = data.get('industry', 'N/A')
        
        html_template = f"""
        <html>
            <head>
                <style>
                    @page {{
                        size: A4;
                        margin: 2.5cm;
                        @bottom-right {{
                            content: "Page " counter(page) " of " counter(pages);
                            font-size: 9pt;
                            color: #95a5a6;
                        }}
                    }}
                    body {{ font-family: 'Helvetica', 'Arial', sans-serif; line-height: 1.7; color: #2c3e50; }}
                    
                    .cover-page {{ 
                        height: 90vh; 
                        display: flex; 
                        flex-direction: column; 
                        justify-content: center; 
                        text-align: center; 
                        border: 10px solid #f1f2f6;
                        padding: 50px;
                    }}
                    .cover-title {{ font-size: 42pt; font-weight: 800; color: #1e3799; margin-bottom: 20px; }}
                    .cover-subtitle {{ font-size: 20pt; color: #4a69bd; margin-bottom: 40px; }}
                    .cover-meta {{ font-size: 14pt; color: #6a89cc; }}
                    
                    h1 {{ color: #1e3799; border-bottom: 3px solid #4a69bd; padding-bottom: 15px; page-break-before: always; }}
                    h2 {{ color: #0c2461; margin-top: 35px; font-size: 18pt; border-left: 5px solid #1e3799; padding-left: 15px; }}
                    p {{ margin-bottom: 15px; text-align: justify; }}
                    
                    .content-section {{ margin-bottom: 40px; }}
                    .footer {{ position: fixed; bottom: -1cm; width: 100%; text-align: center; font-size: 9pt; color: #95a5a6; }}
                </style>
            </head>
            <body>
                <div class="cover-page">
                    <div class="cover-title">Business Strategic Plan</div>
                    <div class="cover-subtitle">{company_name}</div>
                    <div class="cover-meta">Industry: {industry}</div>
                    <div class="cover-meta" style="margin-top: 100px;">Generated by Udyame AI Architect</div>
                </div>

                <h1>Executive Overview</h1>
        """
        
        for item in data.get('answers', []):
            html_template += f"""
            <div class="content-section">
                <h2>{item['question']}</h2>
                <p>{item['answer']}</p>
            </div>
            """
            
        html_template += """
                <div class="footer">Confidential - Generated for internal business planning purposes.</div>
            </body>
        </html>
        """
        
        pdf_stream = BytesIO()
        HTML(string=html_template).write_pdf(pdf_stream)
        return pdf_stream.getvalue()

    def generate_excel(self, data: Dict[str, Any]) -> bytes:
        """
        Generates an Excel workbook for structured data analysis.
        """
        wb = Workbook()
        ws = wb.active
        ws.title = "Business Planning Data"
        
        # Header
        ws.append(["Category/Question", "Response"])
        
        # Data
        for item in data.get('answers', []):
            ws.append([item['question'], item['answer']])
            
        # Basic Formatting
        from openpyxl.styles import Font
        for cell in ws[1]:
            cell.font = Font(bold=True)
            
        file_stream = BytesIO()
        wb.save(file_stream)
        return file_stream.getvalue()

    def upload_to_storage(self, file_content: bytes, file_name: str, bucket: str = "exports") -> Optional[str]:
        if not self.client:
            logger.warning("MinIO client not available. Cannot upload.")
            return None
            
        try:
            # Ensure bucket exists
            if not self.client.bucket_exists(bucket):
                self.client.make_bucket(bucket)
            
            self.client.put_object(
                bucket,
                file_name,
                BytesIO(file_content),
                len(file_content)
            )
            return f"{bucket}/{file_name}"
        except Exception as e:
            logger.error(f"Upload Error: {e}")
            return None

export_service = ExportService()

@celery_app.task(name="app.services.export_service.run_export_task")
def run_export_task(data: Dict[str, Any], format: str = "markdown"):
    """
    Background task for document generation and storage.
    """
    try:
        if format == "markdown":
            content = export_service.generate_markdown(data)
            ext = "md"
        elif format == "docx":
            content = export_service.generate_docx(data)
            ext = "docx"
        elif format == "pdf":
            content = export_service.generate_pdf(data)
            ext = "pdf"
        elif format == "excel":
            content = export_service.generate_excel(data)
            ext = "xlsx"
        else:
            return {"status": "error", "message": f"Unsupported format: {format}"}
            
        file_name = f"export_{uuid.uuid4()}.{ext}"
        storage_path = export_service.upload_to_storage(content, file_name)
        
        return {
            "status": "success",
            "file_name": file_name,
            "storage_path": storage_path,
            "format": format
        }
    except Exception as e:
        logger.error(f"Export task failed: {e}")
        return {"status": "error", "message": str(e)}
