version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: udyame_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=udyame_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5013:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
